version: "3.0"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - app-network

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

  client:
    stdin_open: true
    container_name: client
    build:
      context: ../client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ../client:/var/www/html/
    networks:
      - app-network

  webserver:
    depends_on:
      - backend
      - client
      - pgsql
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
volumes:
  postgres_data:
